### ISSUE TITLE
Add CFLAG -fPIC compiler in Makefile

### ISSUE THREAD

**Issue by jmari** [PierceNg/PasswordCrypt#1]
On Linux Ubuntu 16.4 (Digital Ocean) I had this output trying to compile:

/usr/bin/ld: /tmp/cctjVSzX.o: relocation R_X86_64_32S against `.rodata`can not be used when making a shared object; recompile with -fPIC

I added -fPIC flag in Makefile and the library was generated without errors.

**Comment by PierceNg** [comment]
Thanks. I've added the flag to the Makefile.
